name: Verify PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Test
        run: make test

  verifyDeploy:
    needs: verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install
        run: make OS_ARCH=linux_amd64 install

      - name: Set up terraform cli
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8

      - name: Apply terraform
        env:
          TF_VAR_git_host: github.com
          TF_VAR_git_org: cloud-native-toolkit-test
          TF_VAR_git_username: ${{ secrets.GIT_ADMIN_USERNAME }}
          TF_VAR_git_token: ${{ secrets.GIT_ADMIN_TOKEN }}
          TF_LOG_PROVIDER_gitops: DEBUG
        run: |
          cd examples
          terraform init || exit 1
          terraform apply -auto-approve
          
          echo "***"
          echo "*** Validating terraform apply ***"
          echo "***"
          ../.github/scripts/validate-deploy.sh

      - name: Destroy terraform
        if: ${{ always() }}
        env:
          TF_VAR_git_host: github.com
          TF_VAR_git_org: cloud-native-toolkit-test
          TF_VAR_git_username: ${{ secrets.GIT_ADMIN_USERNAME }}
          TF_VAR_git_token: ${{ secrets.GIT_ADMIN_TOKEN }}
          TF_LOG_PROVIDER_gitops: DEBUG
        run: |
          cd examples
          terraform destroy -auto-approve

  verifyAll:
    needs: verifyDeploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "Success"
